### ISSUE TITLE
Register Page allignment issue

### ISSUE THREAD

**Issue by aneesmhmd** [Solvusphere/solvusphere_client#8]
There is an allignment issue in the input of login page. Like I gave in the screenshot, when the input field is onBlur and not validated, the input field is moving upwards slightly.

![Screenshot from 2023-11-10 19-25-47](https://github.com/Solvusphere/solvusphere_client/assets/121392054/323001dd-fda9-40ec-ab9a-790b3339e5af)

**Comment by Fawaskp** [comment]
Thank you for noticing , it fixed now 👍
